packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@apollo/client": 4.1.4
  "@apollo/client-integration-nextjs": ^0.14.4
  "@commitlint/cli": 20.4.1
  "@commitlint/config-conventional": 20.4.1
  "@eslint/js": 10.0.1
  "@graphql-codegen/cli": 6.1.1
  "@graphql-codegen/client-preset": 5.2.2
  "@ianvs/prettier-plugin-sort-imports": 4.7.1
  "@mantine/core": 8.3.14
  "@mantine/dates": 8.3.14
  "@mantine/form": 8.3.14
  "@mantine/hooks": 8.3.14
  "@mantine/modals": 8.3.14
  "@mantine/notifications": 8.3.14
  "@next/bundle-analyzer": 16.1.6
  "@next/env": 16.2.4
  "@next/eslint-plugin-next": 16.2.4
  "@playwright/test": 1.58.2
  "@tabler/icons-react": ^3.36.1
  "@tailwindcss/postcss": 4.1.18
  "@tanstack/react-query": 5.90.20
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  "@testing-library/user-event": 14.6.1
  "@types/node": 20.19.33
  "@types/react": 19.2.13
  "@types/react-dom": 19.2.3
  "@typescript-eslint/eslint-plugin": 8.55.0
  "@typescript-eslint/parser": 8.55.0
  "@typescript-eslint/type-utils": 8.55.0
  "@typescript-eslint/utils": 8.55.0
  "@vitejs/plugin-react": 6.0.1
  "@vitest/coverage-v8": 4.1.4
  "@vitest/eslint-plugin": 1.6.16
  "@vitest/ui": 4.1.4
  babel-plugin-react-compiler: ^1.0.0
  cz-git: ^1.12.0
  dayjs: ^1.11.19
  eslint: 9.39.2
  eslint-config-mantine: ^4.0.3
  eslint-config-next: 16.2.6
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  eslint-plugin-jest-dom: 5.5.0
  eslint-plugin-only-warn: 1.1.0
  eslint-plugin-prettier: 5.5.5
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.5.0
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-testing-library: 7.15.4
  eslint-plugin-turbo: 2.8.3
  eslint-plugin-unused-imports: 4.4.1
  globals: 17.3.0
  graphql: 16.12.0
  husky: ^9.1.7
  jsdom: 29.0.2
  lint-staged: ^16.4.0
  msw: 2.12.9
  next: 16.2.6
  postcss: ^8.5.14
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  prettier: 3.8.1
  prettier-plugin-packagejson: 3.0.0
  prettier-plugin-pkg: ^0.21.2
  prettier-plugin-tailwindcss: ^0.7.2
  react: 19.2.4
  react-dom: 19.2.4
  react-error-boundary: 6.1.0
  react-hook-form: 7.71.1
  sort-package-json: 3.6.1
  stylelint: 17.3.0
  stylelint-config-standard-scss: 17.0.0
  tailwindcss: 4.1.18
  turbo: 2.8.3
  typescript: ^5.9.3
  typescript-eslint: 8.55.0
  validate-branch-name: 1.3.2
  vite: 8.0.12
  vitest: 4.1.4
  zod: 4.3.6
ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

catalogMode: strict
cleanupUnusedCatalogs: true
