// This file is auto-generated by GraphQL Code Generator
// Run: pnpm run codegen (from packages/graphql)
//
// Phase 1: Placeholder file
// Phase 2: Will contain generated types and hooks from GraphQL schema

export {};
